export const dialogos = [
	[
		["Olá! Tudo bem?"],
		["Eu sou seu novo amigo."],
		["Pode me chamar de Android"],
		["Vou lhe mostrar um pouco sobre a Fisica  e suas forças."],
		["As forças físicas antes de tudo possuem uma classificação:"],
		["Força de contato e força de campo."],
		["Força de campo é quando não existe contato com o objeto ao exercer a força"],
		["Força de contato é quando existe a necessidade do contato ao movimentar o corpo"],
		["Vamos fazer um exercício para você fixar bem agora?"],
	],
	[
		["Na primeira fase do jogo, vimos o que é força de contato e força de campo."],
		["Nesta segunda fase verá a atuação de uma das forças de campo que é chamada de força gravitacional e como atua e sua importância para nós."],
		["Força Gravitacional é a força de atração que existe entre todos os corpos com massa no universo."],
		["É muito pequena.  Só pode ser percebida quando, pelo menos um dos corpos possui massa muito grande, como a de um planeta."],
		["Tudo que tem massa, tem força gravitacional."],
		["Esta força depende sempre da massa dos corpos e da distância entre eles."],
		["A Terra atrai tudo que tem massa, para o centro dela."],
		["Isaac Newton em 1687, propôs a Lei da Gravitação Universal. "],
		["Segundo a lenda, quando teve a experiência de ver a maçã cair da árvore."],
		["Ele concluiu que os corpos que caem, são atraídos pela Terra, com uma força chamada gravidade, que é dirigida para o centro dela."],
		["Agora com base no que você aprendeu até aqui, vamos fazer alguns exercícios?"],
	],
	[
		["A Força Gravitacional é responsável por prender objetos à superfície de planetas e, mantê-los em órbita girando ao redor do Sol."],
		["Quanto maior a órbita, menor a força gravitacional entre eles."],
		["Ela existe entre a Terra e a Lua, Terra e o Sol, Lua e Sol, fazendo com que o movimento de translação da Terra aconteça. "],
		["Newton também chamou a Força Gravitacional de Força Centrípeta a qual, define por uma Força que atua num corpo em movimento circular no sentido de atraí-lo para o centro, em direção ao centro de rotação."],
		["Vamos praticar mais um pouco?"],
	],
	[
		["Força Gravitacional é diretamente proporcional às massas e inversamente proporcional ao quadrado da distância entre os corpos. "],
		["Com a mesma força que a terra atrai você, você atrai a terra."],
		["Apesar da diferença de tamanho, entre você e a terra, as forças de atração gravitacional têm a mesma intensidade, mas a aceleração é diferente, pelo valor das massas dos corpos."],
		["É a gravidade é o que nos faz ter peso. Quando sobe numa balança, ela vai medir a sua massa, que é dada em quilogramas - Kg."],
		['Portanto o correto é dizer "vou subir na balança para verificar minha massa."'],
		["Já o peso é definido, pela gravidade do local e a altitude que você se encontra."],
		["Ex. As pessoas aparentam mais leves na Lua do que na Terra, pois a gravidade da Lua é menor que a da Terra."],
		["Mas, as massas delas continuam a mesma, em qualquer lugar que estejam."],
		["Uma pessoa localizada na linha do Equador pesa menos, do que se ela estivesse localizada nos polos da Terra, pois nos polos ela fica mais próxima do centro da terra,por causa do seu formato achatado. "],
		["Portanto a atração é maior nos polos. Esta diferença é de aproximadamente 0,35%."],
		["O que significa que uma pessoa que pesa 100 Kg nos polos da Terra, pode pesar 99,65 kg na linha do Equador."],
		["O peso é medido em Quilograma-força (Kgf), em Newton(N) ou em dina(dyn)."],
		["Agora vamos praticar."],
	],
	[
		["Podemos comparar a ação da Força de Atração Gravitacional com a queda livre."],
		["Quando os planetas estão em órbita em torno do Sol eles estão “caindo” em direção ao Sol, mas como suas velocidades são muito grandes e fazem ângulo de 90º com a força gravitacional,"],
		["suas distâncias em relação ao Sol permanecem aproximadamente constantes."],
		["O motivo dos astronautas flutuarem, é devido a sua queda livre, ou seja, quando estão em órbita da Terra, a gravidade terrestre os atrai."],
		["Devido a sua enorme massa, o Sol tende a atrair os planetas em sua direção."],
		["Quanto mais próximo do Sol, maior a velocidade do planeta, para que possa escapar do campo de atração gravitacional do Sol."],
		["A Força gravitacional que atua sobre cada um dos planetas explica as trajetórias elípticas, que os faz curvar, permanecendo assim em suas órbitas."],
	],
	[
		["Em virtude da gravidade, a Lua é atraída para o centro da Terra e sofre uma aceleração, a qual produz a sua órbita. São as fases da Lua."],
		["O campo gravitacional do Sol e da Lua não é constante."],
		["Alguns pontos da Terra, em determinada época do ano, estão mais próximos e outros mais distantes destes corpos celestes."],
		["O Fenômeno das marés é um exemplo."],
		["Ocorre devido ao movimento periódico da lua causando assim maior ou menor atração pelas águas."],
		["Quando a Lua está próxima as marés são altas e quando ela se afasta as marés são baixas."],
		["Newton, usou a fórmula F = G. M1.M2/d2 para explicar esse fenômeno natural."],
	],
]